name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Print diagnostic information
        echo "Current directory: $(pwd)"
        ls -la
        # Install direct dependencies first to ensure they're available
        pip install pydantic>=2.0.0 tqdm python-magic python-docx PyPDF2 llama-index openai click rich
        # Install the package in development mode
        pip install -e .
        # Install test dependencies
        pip install pytest pytest-cov flake8 black
        # Verify installations
        pip list | grep pydantic
        pip list | grep tqdm

    - name: Lint with flake8
      run: |
        flake8 src/llm_organizer --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Check formatting with black
      run: |
        black --check src/llm_organizer tests

    - name: Run tests
      run: |
        # Add python path explicitly and list directory contents for debugging
        ls -la src/llm_organizer/core/
        PYTHONPATH=src pytest tests/ --cov=llm_organizer -v
      env:
        # Use dummy API key for testing
        OPENAI_API_KEY: 'sk-dummy-key-for-testing'
